#!/bin/bash

# Define constants
CONFIG_DIR="$HOME/.config"
ZSH_PLUGINS_DIR="$CONFIG_DIR/zsh"
PKG_LIST="pkglist.txt"
AUR_LIST="aur.txt"

# Define functions
install_required_programs() {
    sudo pacman -S zsh kitty xorg-xrdb bat btop lsd tree --needed --noconfirm
}

copy_configuration_files() {
    cp -r .config/* "$CONFIG_DIR"
}

install_zsh_plugins() {
    git clone https://github.com/zsh-users/zsh-history-substring-search "$ZSH_PLUGINS_DIR/zsh-history-substring-search"
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_PLUGINS_DIR/zsh-syntax-highlighting"
    git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_PLUGINS_DIR/zsh-autosuggestions"
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$ZSH_PLUGINS_DIR/powerlevel10k"
    git clone https://github.com/KulkarniKaustubh/fzf-dir-navigator "$ZSH_PLUGINS_DIR/fzf-dir-navigator"
    curl https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh --output ~/.config/zsh/fzf-keybindings.zsh
}

install_bash_insulter() {
    git clone https://github.com/hkbakke/bash-insulter.git bash-insulter
    sudo mv bash-insulter/src/bash.command-not-found /etc/
}

change_default_shell() {
    chsh -s "$(which zsh)"
}

install_starship_prompt() {
    sudo sh -c "$(curl -fsSL https://starship.rs/install.sh)"
}

merge_xresources() {
    xrdb merge "$CONFIG_DIR/x11/Xresources"
}

install_btop_theme() {
    sudo mkdir -p /usr/share/btop/themes
    wget https://raw.githubusercontent.com/catppuccin/btop/main/catppuccin_mocha.theme && sudo mv catppuccin.theme /usr/share/btop/themes
}

copy_pacman_hooks() {
    sudo mkdir -p /etc/pacman.d/hooks
    sudo cp etc/pacman.d/hooks/* /etc/pacman.d/hooks
    sed -i "s/admin/$USER/" /etc/pacman.d/hooks/pkglist.hook
    sed -i "s/admin/$USER/" /etc/pacman.d/hooks/aur.hook
}

install_pkglist_programs() {
    echo "Install programs from $PKG_LIST?"
    read install_pkglist
    [ "$install_pkglist" = "y" ] && sudo pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort "$PKG_LIST"))
}

install_aur_programs() {
    echo "Install programs from $AUR_LIST?"
    read install_aur
    [ "$install_aur" = "y" ] && paru -S --needed - < "$AUR_LIST"
}