#!/bin/sh

# ls 
alias lla='lsd -alh' 
alias ls='lsd -h'
alias la='lsd -A'
alias l.="lsd -a | grep '^\.'"
alias ll='lsd -l'

# Verbosity and settings.
alias cp="cp -iv"
alias mv='mv -iv'
alias rm='rm -vI'
alias df='df -h' 
alias mkdir='mkdir -pv'

# Abbreviate commands.
alias zshrc='nvim ~/.config/zsh/.zshrc'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com' 
alias jctl="journalctl -p 3 -xb" 
alias pastebin="curl -F 'f:1=<-' ix.io"
alias ssn='sudo shutdown now'

# Colorize the commands
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -colour=auto'

# git                
alias addup='git add -u'      
alias addall='git add .'      
alias commit='git commit -m'  
alias push='git push'         
alias stat='git status'       

alias cat='bat' 

# doas not required for some system commands.
for command in mount umount updatedb su shutdown poweroff reboot ; do
	alias $command="doas $command"
done; unset command

# dot
dot() { du -a ~/.config | awk '{print $2}' | grep -vE 'libreoffice|Bitwarden|BraveSoftware|VSCodium|VirtualBox' | fzf | xargs -r nvim ;}

# gitr
gitr() { du -a ~/Documents/git --exclude=".git" | awk '{print $2}' | fzf | xargs -r nvim ;}

#fman
fman() {
    man -k . | fzf --prompt='Man> ' | awk '{print $1}' | xargs -r man
}
